baseURL = 'https://mia-mandarin.github.io/'
languageCode = 'en-us'
title = 'Mia Mandarin Toolbox'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "JSON"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = true
    notAlternative = true
